export const facial = [
	{ treatment: "Mesoterapia facial", price: 500 },
	{ treatment: "Plasma rico en plaquetas", price: 900 },
	{ treatment: "Mesoterapia francesa", price: 500 },
	{ treatment: "Botox", price: 500 },
	{ treatment: "Baby botox", price: 500 },
	{ treatment: "Rellenos / Fillers", price: 500 },
	{ treatment: "Rinomodelacion", price: 500 },
	{ treatment: "Relleno de labios (Tecnica rusa)", price: 500 },
	{ treatment: "Relleno de ojeras", price: 500 },
	{ treatment: "Limpieza facial profunda", price: 500 },
	{ treatment: "Peeling medico", price: 500 },
	{ treatment: "Microdermoabrasion", price: 500 },
	{ treatment: "Punta de diamante", price: 500 },
];
export const capilar = [
	{ treatment: "Tratamiento capilar protocolizado", price: 500 },
	{ treatment: "Hair loss solution", price: 500 },
	{ treatment: "Plasma rico en plaquetas capilar", price: 900 },
	{ treatment: "Dutasteride", price: 500 },
	{ treatment: "Alta frecuencia capilar", price: 500 },
	{ treatment: "Gorro de ozonoterapia capilar", price: 500 },
];
export const corporal = [
	{ treatment: "Mesoterapia lipolipica", price: 500 },
	{ treatment: "Mesoterapia para flacidez cutanea y muscular", price: 500 },
	{ treatment: "Tratamientos protocolizados para estrias", price: 500 },
	{ treatment: "Retensado muscular", price: 500 },
	{ treatment: "Tratamientos protocolizados para aumento de masa muscular glutea", price: 500 },
	{ treatment: "Mesoterapia anticelulitico", price: 500 },
	{ treatment: "Hormonal - Ginecologico colocacion de peelet hormonal", price: 500 },
	{ treatment: "Masajes descontracturantes / relajantes", price: 500 },
	{ treatment: "Reflexologia", price: 500 },
	{ treatment: "Drenaje linfatico", price: 500 },
	{ treatment: "Depilacion descartable", price: 500 },
];
export const aparatologia = [
	{ treatment: "Radiofrecuencia facial y corporal", price: 500 },
	{ treatment: "Ultracavitacion", price: 500 },
	{ treatment: "Body up", price: 500 },
	{ treatment: "Depilacion Definitiva (Soprano ICE)", price: 500 },
	{ treatment: "Ondas rusas", price: 500 },
	{ treatment: "Ozonoterapia", price: 500 },
	{ treatment: "Lipolaser", price: 500 },
];
